/*
 * Kaia Mac
 * Find the average of numbers
 * October 29, 2018
 */

/**
 *
 * @author kamac8665
 */
public class FormShowWhatYouKnow extends javax.swing.JFrame {

    /**
     * Creates new form FormShowWhatYouKnow
     */
    public FormShowWhatYouKnow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        infoLabel = new javax.swing.JLabel();
        courseMark1Label = new javax.swing.JLabel();
        courseMark2Label = new javax.swing.JLabel();
        courseMark3Label = new javax.swing.JLabel();
        courseMark4Label = new javax.swing.JLabel();
        courseMark5Label = new javax.swing.JLabel();
        courseMarkInput1 = new javax.swing.JTextField();
        courseMarkInput2 = new javax.swing.JTextField();
        courseMarkInput3 = new javax.swing.JTextField();
        courseMarkInput4 = new javax.swing.JTextField();
        courseMarkInput5 = new javax.swing.JTextField();
        calculateButton = new javax.swing.JButton();
        averageLabel = new javax.swing.JLabel();
        averageOutputLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backgroundPanel.setBackground(new java.awt.Color(204, 255, 255));
        backgroundPanel.setForeground(new java.awt.Color(204, 255, 255));

        titleLabel.setFont(new java.awt.Font("Tekton Pro Ext", 3, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(0, 0, 51));
        titleLabel.setText("Course Mark Average Calculator");

        infoLabel.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        infoLabel.setText("Enter in five course marks and click Calculate Average.");

        courseMark1Label.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        courseMark1Label.setText("Course Mark 1:");

        courseMark2Label.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        courseMark2Label.setText("Course Mark 2:");

        courseMark3Label.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        courseMark3Label.setText("Course Mark 3:");

        courseMark4Label.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        courseMark4Label.setText("Course Mark 4:");

        courseMark5Label.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        courseMark5Label.setText("Course Mark 5:");

        courseMarkInput1.setText("0.0");

        courseMarkInput2.setText("0.0");

        courseMarkInput3.setText("0.0");

        courseMarkInput4.setText("0.0");

        courseMarkInput5.setText("0.0");

        calculateButton.setText("Calculate Average");
        calculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateButtonActionPerformed(evt);
            }
        });

        averageLabel.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        averageLabel.setText("Your Average is:");

        averageOutputLabel.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        averageOutputLabel.setText("0.0%");

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(infoLabel)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(calculateButton)
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(courseMark2Label)
                            .addComponent(courseMark1Label)
                            .addComponent(courseMark3Label)
                            .addComponent(courseMark4Label)
                            .addComponent(courseMark5Label))
                        .addGap(18, 18, 18)
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(courseMarkInput1)
                            .addComponent(courseMarkInput2)
                            .addComponent(courseMarkInput3)
                            .addComponent(courseMarkInput4)
                            .addComponent(courseMarkInput5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(46, 46, 46)
                .addComponent(averageLabel)
                .addGap(18, 18, 18)
                .addComponent(averageOutputLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoLabel)
                .addGap(28, 28, 28)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(courseMark1Label)
                    .addComponent(courseMarkInput1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(courseMark2Label)
                    .addComponent(courseMarkInput2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(courseMark3Label)
                    .addComponent(courseMarkInput3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(courseMark4Label)
                    .addComponent(courseMarkInput4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(courseMark5Label)
                    .addComponent(courseMarkInput5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calculateButton)
                    .addComponent(averageLabel)
                    .addComponent(averageOutputLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateButtonActionPerformed
        //initializing an array called marks
        double [] marks = new double [5];
            //declaring the value of the index
            marks [0] = Double.parseDouble(courseMarkInput1.getText());
            marks [1] = Double.parseDouble(courseMarkInput2.getText());
            marks [2] = Double.parseDouble(courseMarkInput3.getText());
            marks [3] = Double.parseDouble(courseMarkInput4.getText());
            marks [4] = Double.parseDouble(courseMarkInput5.getText());
        //declaring variables
        double total = 0;
        double average;
            //finding the total of the marks
            for(int i = 0; i <= 4; i = i+1)
            {
                total = total + marks[i];
            }
        //Finding the average of the 5 marks   
        average = total/5;
        
        average = average*10;
        average = Math.round(average);
        average = average/10;
        //setting the text to the average
        averageOutputLabel.setText(average + "%");
        
    }//GEN-LAST:event_calculateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormShowWhatYouKnow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormShowWhatYouKnow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormShowWhatYouKnow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormShowWhatYouKnow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormShowWhatYouKnow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel averageLabel;
    private javax.swing.JLabel averageOutputLabel;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JButton calculateButton;
    private javax.swing.JLabel courseMark1Label;
    private javax.swing.JLabel courseMark2Label;
    private javax.swing.JLabel courseMark3Label;
    private javax.swing.JLabel courseMark4Label;
    private javax.swing.JLabel courseMark5Label;
    private javax.swing.JTextField courseMarkInput1;
    private javax.swing.JTextField courseMarkInput2;
    private javax.swing.JTextField courseMarkInput3;
    private javax.swing.JTextField courseMarkInput4;
    private javax.swing.JTextField courseMarkInput5;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
